### PR TITLE
Add new AO and Tonemap implementation

### PR DESCRIPTION
**Pull request by KosRud**
New AO and Tonemap implementation.

AO uses 2d screen space disk sampling, then extracts world-space coordinates of sampled points and calculates occlusion. Using 2d disk allows optimal sampling and makes it trivial to ensure that all points within the disk are equally likely to be sampled through random jittering.

Tonemap combines Reinhard compression curve with S-shaped contrast curve to achieve a curve shape similar to filmic with a toe and a shoulder, controlled through intuitive parameters.

### CODE REVIEW

**Comment by crosire** [comment]
You are better off hosting these standalone in your own repository (e.g. like https://github.com/BlueSkyDefender/AstrayFX or https://github.com/luluco250/FXShaders), since the `master` branch of this one is deprecated and no longer updated.
You can then add a link to that repository to https://www.pcgamingwiki.com/wiki/ReShade#List_of_known_shader_repositories and I'll see to adding it to the list of repositories the official ReShade setup tool displays.

**Comment by ConstantineRudenko** [comment]
Can it be a folder in a repository, or does it have to be a repository dedicated ONLY to Reshade shaders? I'd like to keep shaders for Reshade and ENBSeries  together.

**Comment by crosire** [comment]
It technically can be a folder in a repository: The setup tool downloads the repository, then searches for a directory called "Shaders". If it finds one, that will be installed, if not it instead searches for the first file with a ".fx" extension and installs the whole directory that file resides in. So if your ReShade shaders are all in one directory and that directory is either called "Shaders" (can be in a subdirectory somewhere too) or is generally the first alphabetically, then it will work.

**Comment by ConstantineRudenko** [comment]
I added the repository to the list.
https://github.com/ConstantineRudenko/Shaders

**Pull request closed without merging**
