### PR TITLE
prod80 shader additions

### PR DESCRIPTION
**Pull request by prod80**
For ReShade

Filmic Tonemapping with exposure correction & Adaptation
Bloom
Color Effects
Sharpening
Helper Functions

### CODE REVIEW

**Comment by prod80** [comment]
> Suggest using log-avg (geometric mean ) for average scene luminance as suggested in reference.

Thanks. Please check CalcExposedColor() function in helper file. It takes log2 of the average scene luminance for exposure compensation.

**Comment by kingeric1992** [comment]
>  It takes log2 of the average scene luminance

That ( `Log2Exposure()` ) is to convert linear avg lum to log space only. In your implementation, avg lum is still generated from arithmetic mean, instead of proposed geometry-mean of pixels luminance.

To be specific, the CalcExposedColor() requires linear-space log-avg luminance, which was applied by Reinhard et al. and later widely used in scene luminance awareness algorithms, as input src as shown in your ref and also described in related articles.
[ref1](https://mynameismjp.wordpress.com/2011/08/10/average-luminance-compute-shader/)
* the Reinhard's paper has typo on the function imo, so I'll leave it be

and as commented in your ref by MJP ( later feed to CalcExposedColor() and ToneMap() )
[ref0](https://github.com/TheRealMJP/BakingLab/blob/master/BakingLab/ToneMapping.hlsl)

and your other ref by Hennessy  ( weighted log-avg )
[ref2](https://placeholderart.wordpress.com/2014/12/15/implementing-a-physically-based-camera-automatic-exposure/)

here's an example on retrieving log-avg in your current setup with minimum modification
```
float PS_WriteLuma(float4 pos : SV_Position, float2 texcoord : TEXCOORD) : SV_Target
{
  float4 color     = tex2D( samplerColor, texcoord );
  float luma       = getMaxLuminance( color.xyz );
  luma             = luma + 0.0001f; 
  return log2(luma); 
}
```

```
float PS_AvgLuma(float4 pos : SV_Position, float2 texcoord : TEXCOORD) : SV_Target
{
  float luma_exp   = tex2Dlod( samplerLuma, float4(0.5f, 0.5f, 0, 8 )).x;
  float luma       = exp2(luma_exp); //linear space log-avg luminance
  float prevluma   = tex2D( samplerPrevAvgLuma, float2( 0.5f, 0.5f )).x;
  float fps        = 1000.0f / Frametime;
  float delay      = fps * ( setDelay / 2.0f );	
  float avgLuma    = lerp( prevluma, luma, 1.0f / delay );
  return avgLuma;
}
```

**Comment by prod80** [comment]
I will check this out, but the difference isn’t going to be large in current build. Equally important is to convert the texture used to read average luminance from sRGB to Linear. Currently it’s reading sRGB texture. Also, maybe more importantly, the output (or expected output) still works even though not following best practices to the letter.

**Comment by prod80** [comment]
Just checked, and there’s no difference between using log avg scene luminance and putting an exp2 before processing it, or just working with the current code. I can possibly see a difference when using it in HDR and having to deal with values over 1.0, but <= 1.0 there seems to be no change.

We should also consider that we are working on top of whatever adaptation algorithm is already present in the game engine. So at most we can enhance or slightly adapt how it works.

I’ll change the code to conform to best practices, but it’s rather a nicety than necessity.

**Comment by prod80** [comment]
- Updated the files to use log2 as suggested
- Edited the bloom fx shader to give better result

**Comment by Wicked-Folie** [comment]
Just a quick question, are those prod80's shaders available? I can't find them...

**Comment by prod80** [comment]
> Just a quick question, are those prod80's shaders available? I can't find them...

Contact me on discord/ReShade
Will take some time to find a link in the ReShade repository as we rework how '3rd party` shaders are added

**Pull request closed without merging**
