### PR TITLE
Update Depth3D.fx

### PR DESCRIPTION
**Pull request by BlueSkyDefender**
Depth3D: Harden to help prevent cheating.                                                       -=let me know if I can do more=-

+Cursor Is now Bound to the 3D image only.
+Removed Depth Buffer Debug view to keep users from using this to cheat.
+Basic VR Compatibility added so that it can be used with VR Desktop apps.
+Basic Theater Mode added for Cellphone VR users.
+Renamed many items in the UI to help new users with controlling this shader.
+New Depth Detection Code.
+New Screen Boundary Detection added.
+Edge Handling added from SuperDepth3D

Fixed issues with the UI in Freestyle and automated many functions as I could to reduce UI clutter. The idea was to keep as much of the functionality as possible without sacrificing too much.

Fixed issues with NV System that was causing a black screen on my Testers PC. This was not easy, I had to remote into a user's pc halfway across the world since I needed someone with an NV Card that was able to help me. Seems like this may be an issue for me with porting my other shaders. Thank you, Durante - aka Dorinte & TheGordinho - aka Gordinho

The goal of Depth3D to allow users to experience the world of 3D Gaming by adding real depth to your game. -=This shader requires depth access to work=-

This shader will work with 3D TV, 3D Monitors, and the NEW VR HMDs. The VR Theater experience worth exploring in VR.
Here are two free applications for VR Headsets That I seen people use that anyone can try.
Virtual Space
https://store.steampowered.com/app/703480/Virtual_Space/
Big Screen
https://bigscreenvr.com/help/gettingstarted/sbs3d/

Older games and non-VR games can benefit from being played again with Stereo3D.
I have been working on My 3D Shader for some time now and learned how to improve things over time even with limitations. My hope is to share this experience with as many people as possible.
I would like this shader to be considered as a standard shader to be used as openly as NV discontinued 3DVision Stereo Software. Since I know many users in the 3D community still enjoy 3D gaming.

Please let me know if there is anything I can change.  Thank you.
Image of CrashBandicoot
Noted Issues
One of the things that bug me with Depth3D It's hard to use for new users. So I will be making better tutorials when I have the hardware to do so for VR.

### CODE REVIEW

**Comment by crosire** [comment]
I'm not sure it's a good idea to rename the file, considering that the old name is well known.

**Comment by BlueSkyDefender** [comment]
You are correct, I didn't think of that. Thank you crosire.

I will revert the Name Change. I love feedback like this.

**Comment by crosire** [comment]
I would keep the `Depth3D` technique name too =P. So existing presets aren't broken that much (some variables were renamed, so it cannot be avoided completly, but the majority would still work).

**Comment by BlueSkyDefender** [comment]
Oh ya I didn't think of that. I can fix that when I get home.

**Pull request merged**
