### PR TITLE
Added Quint + RayTraced Global Illumination shaders/textures

### PR DESCRIPTION
**Pull request by Chaython**
Added Quint + RayTraced Global Illumination shaders/textures

### CODE REVIEW

**Comment by CeeJayDK** [comment]
Again - leave it to Marty to submit Martys work.

**Comment by Chaython** [comment]
> 
> 
> Again - leave it to Marty to submit Martys work.

Again leave it to the maintainer to decide. The license permits sharing. Hope a maintainer adds it, as I know many people who were looking for Reshade's RTGI. Especially after digital foundry's spot, and then the constant spam of youtube videos.
I just finally got around to reading into the licensing and realized I could be sharing it.

**Comment by martymcmodding** [comment]
OK I see you are sharing this in bad faith. Crosire will close this PR, I know it, you know it.
Listen, all I can do is ask you nicely, don't do it. I'm a student, this is my only source of income right now, if you want to cheat me out of it, you can, I just ask you not to. The RTGI shader is in early access, and not finished. I also do not want it online anywhere because it's still buggy and I'm actively working on it, any presets will be frequently broken because settings change. I won't keep it in early access forever, as evidenced that my sharpening went from Patreon to free.

**Comment by Chaython** [comment]
It's not bad faith, I know people that want this. The license also permits sharing.
It's evident to the end user that it's in beta/alpha because the revision is 0.x.
Credit is given directly in the readme, so everyone who comes here will see it.
I imagine an increase in subscribers, if the product meets expectations for a beta release.
"I'm a student, this is my only source of income right now" This is a massive source of income $7,780/month I cannot believe you seek pitty. You're in the richest 10% of people.

> A net worth of $93,170 U.S. is enough to make you richer than 90 percent of people around the world, Credit Suisse reports. - https://www.cnbc.com/2018/11/07/how-much-money-you-need-to-be-in-the-richest-10-percent-worldwide.html

**Comment by martymcmodding** [comment]
10 % of people world wide. Not in first world countries.
You are Canadian, I am German. You do not have our tax level. Afaik you also do not have mandatory health insurance worth a shit. I can be happy if a third of it ends up here. I live in a big city with atrocious rent, have to, as my University is here. I also don't use that money for myself only. I don't seek pity, I explain to you my situation. You still have to go out of your way to cause harm. The increase in subscribers will be the opposite, you know it. I program shaders since 2010, Patreon and other donation thing never yielded anything, until it was mandatory. SEUS has been programming shaders for ages as well, his income tendfolded when it became mandatory. When I cannot add anything else to the RT shader and release it publicly, Patreon will flatline. But hey, you can hurt me and my family very much and get away with it and help some people use something a tiny bit earlier than the rest of the world, or not do that.

**Comment by Chaython** [comment]
Delayed releases works great for patreons  - see cemu
You're getting so many donations because buzzwords, marketing and a decent product. Nothing else has been truly interesting about Reshade to the average person.
You're over reaciting if people want newer releases they will subscribe...

**Comment by martymcmodding** [comment]
I guess that's correct. Thing is, you mention in the readme of your own copy that I broke the CC license by distributing it myself commercially - I did not, as seen above.

You probably won't care but let's break it down. 
7780$ a month
minus Patreon fees: 7600ish
Paypal using an absolutely atrocious $/€ conversion: 6400€
Minus taxes with my tax level, mandatory insurances: 3400€
Minus rent for room in one of Germany's biggest cities: 1300€

**Comment by Chaython** [comment]
So register a NPO? PayPal and Patreon give reduced fees to NPOs. + No business tax. Ask a lawyer. I don't know the req. but tons of FOSS are registered as NPO. Further there's ways to stop PayPal from force converting. The best currency conversion rates I could find are with Revolut [mid market. monthly fee above cap]

**Comment by martymcmodding** [comment]
You kind of forget that I am still studying basically full time along with that. I can hardly chip away time to work on this stuff as is, only because it yields so much money right now. As you should know, German bureaucracy is a nightmare.
You really want me to put that much effort into this when you could just...delete it? What is stopping you? I have seen that you uploaded a video earlier this year when you did not know about the licensing stuff where you shared the yiff link - not any Patreon links like "support this guy" as someone in good faith would do that is just advertising it. The only reason I can see is that you want to hurt my income or myself. If Patreon does not yield enough anymore, I will have to stop doing what I do. You are by far not the only one kicking my chair.

**Comment by TreyM** [comment]
Chaython, you are a disgrace. This is pathetic.

**Comment by martymcmodding** [comment]
So I think I found something highly interesting. I read this:

https://creativecommons.org/licenses/by-nc-nd/3.0

and the accompanying actual license full document. You have to add a link to the license, otherwise you're breaking the terms. I only added the "CC BY NC ND 3.0" notice - not its link. That way, I am actually breaking my own license, voiding it. 

Now the actual RT shader has an EULA with it - the one you got probably not, as you got it from god knows where and people like to remove that sort of stuff. If this CC license was valid, it'd null the EULA. But as the CC by itself is null and void because I didn't link the actual license on creativecommons.org, it cannot null the EULA. Which is then valid. And you broke it.

**Comment by TreyM** [comment]
The creative commons license on this is void. The license states that the author MUST provide a link the license. The header contains no such link. With that said, this file is stolen code and you are in direct violation the "DO NOT SHARE" portion of the header.

**Comment by TreyM** [comment]
Your upload of this file has been reported to Github. Anyone else wishing to do the same can do so here: https://github.com/contact/report-content

**Comment by crosire** [comment]
Requiring a license to share code is just plain wrong. You don't need to register anything too. That's a big misconception. Most countries on earth have the concept of intellectual property and anything created by somebody by default belongs to them and it is up to that person to decide how they want to share it with others. This also means nobody else has any rights on such a product until the product owner explicitly grants you rights.
In this case the product owner selected a license that grants some rights they did not actually want to grant and they later retracted that license. As a result in good faith one should not violate the owners decision and therefore these files should not be shared. They are Marty's intellectual property after all and nobody elses.

**Pull request closed without merging**
