### PR TITLE
Reimplement the LUT/MultiLUT as readable code

### PR DESCRIPTION
**Pull request by seri14**

### CODE REVIEW

**Comment by martymcmodding** [comment]
I think you meant to type "unreadable".

**Comment by seri14** [comment]
Try extract

**Comment by martymcmodding** [comment]
What should I extract?

**Comment by seri14** [comment]
`vars.xz = (vars.xz + float2(floor(blueTable), ceil(blueTable))) * (1.0 / fLUT_TileAmount);`
is same as
```
vars.xz += float2(floor(blueTable), ceil(blueTable));
vars.xz /= fLUT_TileAmount;
```

**Comment by CeeJayDK** [comment]
BORDER texture address mode?

I believe that will break the shader. It should be CLAMP, which is the default btw.

**Comment by seri14** [comment]
Actually, not over 1.0. sorry this is debug code.

**Comment by CeeJayDK** [comment]
Seri could you drop by the Discord so you can discuss these changes with the original author (Marty) before you proceed?

Developers have a tendency to get upset if you mess too much with their babies.

It's https://discord.gg/GEb23bD

**Comment by seri14** [comment]
I do not like discuss on not here or forum.
and I seems you already have answer.

**Comment by martymcmodding** [comment]
Sorry I don't already have my answer 🤔 Nothing you said made any sense to me, I'm completely confused. The code changes don't make the code more readable, on the contrary. Adding BORDER as ADDRESSU V (and W for some reason?) is bad and should be left at clamp, which is the default so there's no reason adding it. Nothing in there warrants a rewrite and the code is less readable than before.

**Comment by seri14** [comment]
This PR's point is to reduce of thinking steps.
before code have `color.xy * fLUT_TileSizeXY` and `color.z * fLUT_TileSizeXY`, but the fixed code is once time each in all of uniforms/constants.
and simplified that decide of blue.

**Comment by seri14** [comment]
I think so too about "BORDER". I will remove it.

**Comment by FransBouma** [comment]
I wrote the multiLUT shader, don't really see why it's that unreadable. Sure things are crammed on a single line at times, but storing them in local vars isn't going to help with performance.

**Comment by seri14** [comment]
I understand. thank you for your review.

**Comment by FransBouma** [comment]
Hey @seri14 don't feel bad about this, people often get a little touchy when someone says their code isn't that readable :) To make me understand better and to improve my own code in the future: could you explain a bit why multiLUT wasn't that readable/understandable? It's a shader people make custom adjustments to so maybe we could indeed make it more easy to understand so people can more easily make changes to it to e.g. use their own LUTs.

**Comment by seri14** [comment]
Please keep your sense.
If you post the bad code after my post, I will get strongly hates from all users.

**Comment by FransBouma** [comment]
Not sure I understand, but it's your call :). I don't mind if people say my code is unreadable, I just am interested in why they think that (which can certainly be very legit :) so I can learn and improve for the future, so let me know if you want to discuss this further so your changes (and work you spend on that) isn't lost.

**Pull request closed without merging**
