### PR TITLE
Updated MXAO, added qUINT shaders

### PR DESCRIPTION
**Pull request by Chaython**
Updated MXAO[renamed to qUINT MXAO], added qUINT shaders
Edited read me to give credit to marty for qUINT shaders/textures

### CODE REVIEW

**Comment by Matsilagi** [comment]
Are you crazy?
RTGI is paid and you are uploading it here?
Oh wow...

**Comment by Chaython** [comment]
All shaders stated BY-NC-ND 3.0 licensed; which says 

> You are free to:
> 
>     Share — copy and redistribute the material in any medium or format 

> NonCommercial — You may not use the material for commercial purposes. 

He is using the material for commercial purposes[breaking the license] and the license says you are free to share copy and redistribute.

**Comment by Matsilagi** [comment]
You didn't read the RTGI license, did you? The RT shader isn't.
The others, yes, they are free to use that way, but i don't think he would like those joined on the main repo.

**Comment by Chaython** [comment]
I do not have a copy of the license, I can only comment on the copyright appened to the FXH file which is https://creativecommons.org/licenses/by-nc-nd/3.0/

> The licensor cannot revoke these freedoms as long as you follow the license terms.

The licensing terms cannot contradict the license

**Comment by Matsilagi** [comment]
I see what you did.
You removed the header and replaced the license.
Im sorry, but that doesn't make it correct to upload those, that ain't how it works kid.

I can paste the original header in a comment on your code, or you can remove those. Your choice.

**Comment by Chaython** [comment]
I have not edited the fxh files, this is as they were provided to me.
Perhaps you have a newer revision this is 0.81

**Comment by Matsilagi** [comment]
Yeah, i do have the latest one.
anyways, i don't think he will like this but, we'll see how it will get solved.

**Comment by martymcmodding** [comment]
Yes, it has this license. But the big "PATREON ONLY FILE - DO NOT SHARE" you missed in the main file, right? Good job, you publicly leaked a private access file without even asking me. If I wanted any part of qUINT merged into this branch, I would have done it by so.

**Comment by Chaython** [comment]
The license permits the ability to share, you're not allowed to
> restrict others from doing anything the license permits.

**Comment by martymcmodding** [comment]
Yep, I fucked up license wise. Should not have copypasted that from the other files. All I can really do I ask you kindly not to share it anywhere else - I already asked crosire to deny this pull request. No new versions will have this license, thanks for informing me.

**Comment by martymcmodding** [comment]
I might add, I always keep qUINT and the RT shader same, version wise, so the common file works with both. This version is a mixed old pirated RT shader version + some older qUINT, I suppose? That isn't particulary a good idea, because if mismatching file versions are used, it throws a bunch of errors. The latest pirated RT version is not compatible with latest public qUINT.

**Comment by Chaython** [comment]
It's not piracy if a shareable license was provided. You should just commit the newest revision with a shared license.

**Comment by martymcmodding** [comment]
I edited the license of the RT shader now, future versions will not fall under this CC license until the closed beta is over, then it will join qUINT under this license. What you are commiting there is the 0.8.0.2 version which is incompatible with latest qUINT. While you're right, I cannot forbid you to further share it, future versions don't have this issue. Thanks for letting me know, I should read before copypasting something.

**Comment by Chaython** [comment]
> 
> 
> I edited the license of the RT shader now, future versions will not fall under this CC license until the closed beta is over, then it will join qUINT under this license. What you are commiting there is the 0.8.0.2 version which is incompatible with latest qUINT. While you're right, I cannot forbid you to further share it, future versions don't have this issue. Thanks for letting me know, I should read before copypasting something.

Thanks, please confirm the latest revision, of which the shareable license is removed including hashs'.
Please inform me of the new license, so I can act in accordance to the new license when the revision is provided to me.

**Comment by martymcmodding** [comment]
I'm a bit confused now.

0.8.0.2: CC license
anything higher: will have no CC license, sharing = illegal

So the only way for you to obtain new versions would be via illegal means, so why would you need its license?

**Comment by CeeJayDK** [comment]
Martys shaders in the official repo could need an update so they are more in-line with his latest version, but I think it's best we leave that task to Marty, since he understands his own code the best and probably has his own vision for his work.
It's not like he has abandoned his code or anything.

@martymcmodding Please update your effects on your own time as you see fit.

**Comment by martymcmodding** [comment]
With MXAO I see 3 possibilities:

1) delete MXAO.fx from this repo, add qUINT MXAO -> breaks all presets using MXAO.fx
2) delete MXAO.fx from this repo, add qUINT MXAO, rename techniques so it fits again -> 2 identical versions present, once you decide to mix qUINT in your shader list, you have 2 times MXAO
3) add qUINT MXAO, keep MXAO.fx -> 2 MXAO versions in shader list, one old, one new

There is really no winning here. Since I designed qUINT to be a self-contained system that doesn't really need third party shaders, I don't really want it to be added here. Not every shader needs to be in the example repo.

**Comment by Chaython** [comment]
Depeneding on what licensing is used, it may still be shareable. Many licenses are shareable or non-enforcable. Just because you choose to no longer use CC doesn't mean you will have any more protections. If you're saying you will use no license, and will only use a copyright you must of course register a copyright before any legal actions could be pursued [if a revision is shared prior to registering your copyright; you're going to have little chance in pursuing actions against the sharer].

**Comment by martymcmodding** [comment]
That is true. Thing is, most platforms where something is shared _illegally_ they don't give a damn about legal inquiries as well, and it isn't worth the cost. Platforms obeying copyright laws and especially mod hosters, you can just do a DMCA request and they remove it, as long as it's your intellectual property so you don't even need to add any sort of license. Sonic Ether adds a license to his shaders that seems to be set up by a lawyer, I thought of doing something along the lines of that. It's really not worth the hazzle to sue everyone for a 5 dollar piece of software, I just need the right to use the report form of every platform so they'll remove it. You may not have shared it with ill intentions, but many do it on social media.

**Comment by Chaython** [comment]
As for breaking previous presets, if it brings tangible benefits then that is fine, people can update at there will. Your shaders do not automatically update.
Further the CC license on qUINT_MXAO doesn't give permission to make Derivatives aka I'm not allowed to edit the files under the license. So if you wish to make compatibility you must do it yourself or further remove the CC license, and just express the permission to share the file. The CC license you chose doesn't make sense for git nor commercial.

**Comment by martymcmodding** [comment]
Well, how ReShade is supposed to be used, they do update. You're not supposed to include ReShade or any shaders into a preset when you share it, so people install ReShade, download the shaders (mostly the new versions) and then use the preset. That license did exactly what I wanted it to - because many people kept modifying the code in ways I didn't want to, so I wanted to give myself the only right to modify it, that's why I moved it to an own repo. Why the license ended up in the RT shader - I'm an idiot, that's why. Copypasted existing shaderfiles, removed their content - not the header - and added new code. The only reason why I share my shaders in source code is because you cannot precompile them on your hardware and share them in that form. I use git only because it's easy for these purposes., I never much bought into open source stuff anyways. For commercial purposes, the license makes no sense, that's true.

**Comment by TreyM** [comment]
This is absolutely shameful. You KNEW uploading this was going to be a problem and yet you did it anyway. Leaking a PRIVATE patreon only shader to GitHub that I seriously doubt you had actual access to. You no doubt pirated this, and noticed the license which was clearly an oversight on Marty's part since the public wasn't meant to even see the shaders yet beyond Patreon access.

**Comment by TreyM** [comment]
The creative commons license on this is void. The license states that the author MUST provide a link the license. The header contains no such link. With that said, this file is stolen code and you are in direct violation the "DO NOT SHARE" portion of the header.

**Comment by TreyM** [comment]
Your upload of this file has been reported to Github. Anyone else wishing to do the same can do so here: https://github.com/contact/report-content

**Comment by Fubaxiusz** [comment]
Hello there,
CC license is also used on commercial research papers, with additional licensing terms.
Like in this journal http://jcgt.org/ where people from Disney are submitting papers.
License looks like this:

© 2019 Somebody Name (the Authors).
The Authors provide this document (the Work) under the Creative Commons CC BY-ND
3.0 license available online at http://creativecommons.org/licenses/by-nd/3.0/. The Authors
further grant permission for reuse of images and text from the first page of the Work, provided
that the reuse is for the purpose of promoting and/or summarizing the Work in scholarly
venues and that any reuse is accompanied by a scientific citation to the Work.

Hope it helps.

**Pull request closed without merging**
